@echo off
echo Starting DataOps Inspector servers...

echo Starting backend server...
start "Backend Server" cmd /k "cd backend && python flask_app.py"

echo Starting frontend server...
start "Frontend Server" cmd /k "cd frontend && npm start"

echo Servers are starting...
echo Backend: http://localhost:8000
echo Frontend: http://localhost:3000
echo.
echo Press any key to exit...
pause 